# Release: https://github.com/thepopeblack-byte/cv-website/releases/tag/v1.0.0
# Workflow URL: https://github.com/thepopeblack-byte/cv-website/actions/runs/28288161997
# Commit: https://github.com/thepopeblack-byte/cv-website/commit/0e1e0bdcf34c437d23c4e468476607d64f8f9a1c
# Dockerfile Path: Dockerfile
# Docker Compose Location: ./docker-compose-secretvm.yaml
version: '3'
services:
  app:
    image: ghcr.io/thepopeblack-byte/cv-website@sha256:4251303311aa7206a224c286778754590f6b6263a90b1ff4d3e57791022440e0
    ports:
      - '3000'
